name: 'Hello World'
description: 'Greet someone'

runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash      
    - run: script.sh
      shell: bash
