name: "Hello World"
description: "Greet someone"

runs:
  using: "composite"
  steps:
    - name: Clone bazel-diff repo
      uses: actions/checkout@v3
      with: 
        repository: tinder/bazel-diff
        path: tools

    - name: Run bazel-diff
      run: ${GITHUB_ACTION_PATH}/script.sh
      shell: bash
