name: "Upload Affected Targets"
description: "Upload Affected Targets on a pull-request run. Currently only supports Bazel."

runs:
  using: "composite"
  steps:
    - name: Get bazel-diff Tool
      uses: actions/checkout@v3
      with:
        repository: tinder/bazel-diff
        path:
          /tmp/tools # TODO: this shouldn't be hardcoded.

    - name: Upload Affected Targets
      run: ${GITHUB_ACTION_PATH}/script.sh
      shell: bash
      env:
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        BASE_SHA: ${{ github.event.pull_request.base.sha }}
