name: "Hello World"
description: "Greet someone"

runs:
  using: "composite"
  steps:
    - run: ${GITHUB_ACTION_PATH}/script.sh
      shell: bash  
    - name: Checkout actions repo
      uses: actions/checkout@v3
      with: 
        repository: tinder/bazel-diff
        path: main
    - run: ${GITHUB_ACTION_PATH}/script.sh
      shell: bash
