name: "Hello World"
description: "Greet someone"

runs:
  using: "composite"
  steps:
    - name: Checkout Composite Actions Repo
      uses: actions/checkout@v3
      with:
        repository: nikhilbirmiwal/hello-world-composite-action
        path: tools

    - name: Get bazel-diff Tool
      run: ${GITHUB_ACTION_PATH}/tools/install_bazel_diff.sh
      shell: bash

    # requires that the GITHUB_ACTION_PATH has a WORKSPACE file, which I think is reasonable
    - name: Run bazel-diff
      run: ${GITHUB_ACTION_PATH}/tools/script.sh
      shell: bash
