name: Trunk Upload Affected Targets
author: trunk.io
description: Trunk.io Github Action to upload Affected Targets

runs:
  using: composite
  steps:
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: oracle
        java-version: "17"
      
    - name: Setup Bazel
      uses: bazelbuild/setup-bazelisk@v2

    - name: Upload Affected Targets
      run: ${GITHUB_ACTION_PATH}/upload_affected_targets.sh
      shell: bash
