name: "Upload Affected Targets"
description: "Upload Affected Targets on a pull-request run. Currently only supports Bazel."

runs:
  using: "composite"
  steps:
    - name: Get bazel-diff Tool
      run: ${GITHUB_ACTION_PATH}/install_bazel_diff.sh
      shell: bash

    - name: Upload Affected Targets
      run: ${GITHUB_ACTION_PATH}/script.sh
      shell: bash
      env:
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        BASE_SHA: ${{ github.event.pull_request.base.sha }}
